### ISSUE TITLE
Runtimes

### ISSUE THREAD

**Issue by JosepSampe** [metaspace2020/pywren-annotation-pipeline#10]
I was looking in: https://hub.docker.com/u/ibmfunctions and seems there are 5 diferent runtimes for this notebook. Which are the differences between them? maybe I'm using wrong runtime... Or they are all the same with different names? It's a bit weird..

**Comment by omerb01** [comment]
@JosepSampe these runtimes are all identical, their creations were intended to reduce memory usage before the last pywren's updates

**Comment by omerb01** [comment]
@JosepSampe these runtimes are all identical, their creations were intended to reduce memory usage before the last pywren's updates

**Comment by gilv** [comment]
@JosepSampe only this one https://hub.docker.com/r/ibmfunctions/pywren-metabolomics 
the rest i about to delete...previous experiments, before you implemented new runtime management
