### ISSUE TITLE
update metabolomics docker environment

### ISSUE THREAD

**Issue by omerb01** [metaspace2020/pywren-annotation-pipeline#14]
we need to deploy an updated docker file with the following packages:
```
pandas==0.23.3
pyImagingMSpec==0.1.4
cpyImagingMSpec==0.3.2
pyMSpec==0.1.2
cpyMSpec==0.4.2
pyimzML==1.2.5
```
to prevent PyWren from serialize and store parts of these modules and also to support future usage in `pyMSpec` and `pyimzML`

**Comment by gilv** [comment]
@omerb01 thanks. will handle it.
