### ISSUE TITLE
PyWren result of annotate_segm_spectra is wrong

### ISSUE THREAD

**Issue by intsco** [metaspace2020/pywren-annotation-pipeline#2]
![image](https://user-images.githubusercontent.com/1176502/55554429-0a301900-56e3-11e9-8213-b14866a4403f.png)

**Comment by intsco** [comment]
![image](https://user-images.githubusercontent.com/1176502/55554671-a4905c80-56e3-11e9-9660-8ea80f3bdb39.png)

**Comment by omerb01** [comment]
@intsco I can see in "In [84]" in line 3 that you changed `iterdata` to use only the first 2 segments instead of `segm_n`.
if you splitted the datasets for more than 2 segments, it will annotate only that part of the dataset regardless the others.
you need to change `segm_n` variable and recreate `segments_intervals` and segments in COS

**Comment by intsco** [comment]
If I use `segm_n` when creating `iterdata`, it takes longer but the result is the same

**Comment by omerb01** [comment]
@intsco when I run the notebook on 32 segments with the sample data you provided us I get:
![Screen Shot 2019-04-04 at 19 03 38](https://user-images.githubusercontent.com/13593227/55570595-665b6300-570c-11e9-92b5-cc954b84cbeb.png)
is it the correct result you expect? do you use the same data?
also I get:
![Screen Shot 2019-04-04 at 19 06 06](https://user-images.githubusercontent.com/13593227/55570747-bb977480-570c-11e9-934b-69bdda08af35.png)

**Comment by gilv** [comment]
@intsco what is correct result you expect from that dataset?

**Comment by intsco** [comment]
@gilv , @omerb01 posted expected function outputs. I'm trying to get the same

**Comment by intsco** [comment]
I cloned `pywren-ibm-cloud` from Github and installed it with pip locally. This issue seems to be gone.
