### ISSUE TITLE
input_config.json.template is different from  input_config_XYZ.json

### ISSUE THREAD

**Issue by gilv** [metaspace2020/pywren-annotation-pipeline#21]
input_config_big.json, input_config_huge.json, input_config_small.json has different structure comparing to input_config.json.template. I am not sure why it's like that..should i download dataset (metabolomics.tar.gz) again?  for example getting

KeyError                                  Traceback (most recent call last)
<ipython-input-7-95a710636384> in <module>
      5 input_data = input_config['dataset']
      6 input_db = input_config['molecular_db']
----> 7 output = input_config['output']

KeyError: 'output'

because input_config_small.json  doesn't have "output", while template file has.

@LachlanStuart @omerb01 any input on this?

**Comment by omerb01** [comment]
@gilv now we can commit the input config files, so this issue can be closed.
