### ISSUE TITLE
Update PyWren's runtime for Jupiter

### ISSUE THREAD

**Issue by omerb01** [metaspace2020/pywren-annotation-pipeline#24]
@gilv please add this line to the Dockerfile and deploy the changes:
```
RUN pip install jupyter
```
I found that PyWren serialize its packages (14MB in estimate) every time when it calls for map execution.

**Comment by gilv** [comment]
@omerb01 why we need jupypter in runtime?

**Comment by omerb01** [comment]
@gilv we run the project from Jupyter and PyWren recognize its packages as used in the code, so pywren serializes 14mb of it into COS everytime we execute 'map'.
we can avoid pywren to do so by installing Jupyter in the runtime.

**Comment by gilv** [comment]
@JosepSampe I think i once saw it also..for sure we don't want PyWren to serialize  Jupyter and i also dpon't like to have Jupyter inside runtime, as it has nothing to do real code we running....
do you have some input on this?
