### ISSUE TITLE
alternatives for pd.concat() in define_centr_segments()

### ISSUE THREAD

**Issue by omerb01** [metaspace2020/pywren-annotation-pipeline#51]
something I want to put in a discussion:
https://github.com/metaspace2020/pywren-annotation-pipeline/blob/5a2858b25404c8017155a2f95e5202ef5b9b7be8/annotation_pipeline/segment.py#L202
this line uses `pd.concat()` to gather all mz values from the first peak into the local machine. if we have thousands of centroids segments, it can take a lot of time just for the concatenation - on "huge2" it takes approximately 10min.
is there any alternative way we can define centroids segments bounds?

**Comment by LachlanStuart** [comment]
For this specific instance, there is an easy alternative. Because this code only needs a single column of values, it can just skip using pandas entirely. See the 3 lines with comments:

```python
def define_centr_segments(pw, bucket, clip_centr_chunk_prefix, centr_n, ds_segm_n, ds_segm_size_mb):
    logger.info('Defining centroids segments bounds')

    def get_first_peak_mz(obj):
        print(f'Extracting first peak mz values from clipped centroids dataframe {obj.key}')
        centr_df = pd.read_msgpack(obj.data_stream._raw_stream)
        first_peak_df = centr_df[centr_df.peak_i == 0]
        # Add `.values` on the next line to get the underlying raw 1D numpy array instead of a Pandas series
        return first_peak_df.mz.values

    futures = pw.map(get_first_peak_mz, f'{bucket}/{clip_centr_chunk_prefix}/')
    # Change pd.concat to np.concatenate
    first_peak_df_mz = np.concatenate(pw.get_result(futures))
    append_pywren_stats(futures, pw.config['pywren']['runtime_memory'])

    ds_size_mb = ds_segm_n * ds_segm_size_mb
    data_per_centr_segm_mb = 50
    peaks_per_centr_segm = 1e4
    centr_segm_n = int(max(ds_size_mb // data_per_centr_segm_mb, centr_n // peaks_per_centr_segm, 32))

    segm_bounds_q = [i * 1 / centr_segm_n for i in range(0, centr_segm_n)]
    # Not related, but this line can also be easily simplified/optimized:
    centr_segm_lower_bounds = np.quantile(first_peak_df_mz, segm_bounds_q)

    logger.info(f'Generated {len(centr_segm_lower_bounds)} centroids bounds: {centr_segm_lower_bounds[0]}...{centr_segm_lower_bounds[-1]}')
    return centr_segm_lower_bounds
```

However, I'm really surprised you find `pd.concat` to be slow. I've never had a problem with its speed. I've only had problems with how much memory it uses. 

Are you sure it was `pd.concat`, and not `pw.get_result` that is slow? It could have also been the inefficient way that `np.quantile` was called - the above change should give a significant speed up if there are 1000s of segments.

**Comment by omerb01** [comment]
@LachlanStuart thanks for the changes, I tested it and now it's much better.
previously, with `huge2` dataset, `segment_centroids()` took ~10min and now it takes ~2min with these changes.
yes, on my local machine (Mac) `pd.concat()` is very slow for some reason, maybe it connects to memory allocations. I am very surprised that `np.concatenate()` differs significantly.
I will commit the changes without submitting a PR
