### ISSUE TITLE
Pickle annotation DB for faster reading - do we need this

### ISSUE THREAD

**Issue by gilv** [metaspace2020/pywren-annotation-pipeline#8]
@omerb01 I thought you implemented improvement where the first step prepare DBs by pickle them and annotation_spectra then unpickle DBs files. If i recall correctly this provided speedup for reading those databases...
However i don't see this code in the notebook here.
Am i wrong? Thanks

**Comment by omerb01** [comment]
@gilv right , haven't pushed it yet, will do it soon

**Comment by omerb01** [comment]
Fixed on #9
